spring:
  application:
    name: communityLab
  profiles:
    active: dev

  ai:
    openai:
      api-key: ${API_KEY_LLM_MISTRAL_DEV}
      chat:
        model: ${MODEL_MISTRAL}
      base-url: ${BASE_URL_MODEL_AI}

  output:
    ansi:
      enabled: always

# Value of buffer max batch size
redis:
  buffer:
    max:
      bytes: ${REDIS_BUFFER_MAX_BYTES:921600}

# Configuration Telegram
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    listen-group-id: ${TELEGRAM_LISTEN_GROUP_ID}

# Configuration Scheduler
buffer:
  flush:
    cron: ${BUFFER_FLUSH_CRON:0 0 * * * *}
    min-messages: ${BUFFER_FLUSH_MIN_MESSAGES:5}
    scheduler:
      enabled: ${BUFFER_FLUSH_SCHEDULER_ENABLED:true}
